# Generated by Django 3.2.14 on 2023-01-25 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth1', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth2', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth3', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth4', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth5', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth6', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth7', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth8', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth9', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth10', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth11', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth12', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth13', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth14', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth15', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth16', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth17', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth18', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth19', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth20', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth21', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth22', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth23', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth24', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth25', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth26', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth27', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth28', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth29', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth30', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth31', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('tooth32', models.CharField(choices=[('cleaning', 'cleaning'), ('lorem', 'lorem'), ('ipsom', 'ipsom')], default='lorem', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
